### ISSUE TITLE
After upgrade to 1.5.0, extension not working any more

### ISSUE THREAD

**Issue by kataklys** [liximomo/vscode-sftp#313]
## Expected Behavior
Expected to see the remote explorer icon in the left bar and the usual SFTP-related menu items on right click

## Actual Behavior

after extension upgraded to 1.5.0, remote explorer icon disappeared and when right-clicking a file/dir I have no more sync/download/upload items

## Steps to Reproduce the Problem

 just let the extension upgrade from 1.4.x to 1.5.0

### Extension Logs

Can't reproduce because extension is already upgraded 
Didn't find any logs generated upon startup even with printDebugLog set to true

## Specifications

  - Version: 1.5.0
  - Platform: Ubuntu 16.04.5 LTS

**Comment by liximomo** [comment]
Any log?

**Comment by liximomo** [comment]
Try v.1.5.2. I think this is because of  the case style for file names.

**Comment by mts88** [comment]
> Try v.1.5.2. I think this is because of the case style for file names.

Version 1.5.2 doesn't work for me. Running SFTP: config, trigger error  command 'sftp.config' not found and the extension doesn't recognize the sftp config.

**Comment by jmsosso** [comment]
Same problem here _command 'sftp.config' not found_ also the icon in the left bar disappears...

**Comment by liximomo** [comment]
@mts88 @jmsosso Could you provide some logs?

**Comment by pet3r** [comment]
I have similar problem with 1.5.2.
Automatic synchronisation doesn't work and manual upload trigger error: `command 'sftp.upload.activeFile' not found`

I have set printDebugLog to true, but didn't find any log.

**Comment by mts88** [comment]
> @mts88 @jmsosso Could you provide some logs?
I can't find any log in debug console. 
Downgrading to 1.4.1 suggested by @kataklys works.

**Comment by liximomo** [comment]
@mts88 @kataklys @jmsosso @pet3r @bezbeli I think this should be fixed in v1.5.3.

**Comment by jmsosso** [comment]
> @mts88 @kataklys @jmsosso @pet3r @bezbeli I think this should be fixed in v1.5.3.

Sorry still not working :(

If I run the command _Developper: Show running extensions_ SFTP doesn't appears in the list.

This is what I see in exthost1.log:

```
[2018-09-14 14:09:12.779] [exthost1] [info] ExtensionService#_doActivateExtension liximomo.sftp {"startup":true,"activationEvent":"workspaceContains:.vscode/sftp.json"}
[2018-09-14 14:09:12.779] [exthost1] [info] ExtensionService#loadCommonJSModule /home/jmsosso/.vscode/extensions/liximomo.sftp-1.5.3/out/src/extension
```
But seems the extension is not enabled... but it is. I cannot see nothing more in the logs.

**Comment by liximomo** [comment]
Try 1.5.4.

**Comment by linibou** [comment]
it's fixed for me ! Thank you so much for your great work ! 
I can close FileZilla :-D
Cheers
